# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Vizbot API
  
definitions:
  Entity:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      type:
        type: string
        enum: ['trait', 'freetext', 'keyword']
      color:
        type: string

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /entity:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Add new `Entity` to your app
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: name
          in: formData
          description: Name of Entity
          required: true
          type: string
        -
          name: type
          in: formData
          description: Type of Entity. Can be "Trait", "Freetext", "Keyword"
          required: true
          type: string
          enum: ['trait', 'freetext', 'keyword']
      # Expected responses for this operation:
      responses:
        # Response code
        201:
          description: Successful created
    
    get:
      description: |
        Get all `Entity` that available in your app
      produces:
        - application/json
      responses:
        200:
          description: A list of your availble `Keyword`
          schema:
            type: array
            items:
              $ref: '#/definitions/Entity'
  
  /expression:
    post:
      description: |
        Add new `Expression` for `Entity`
      parameters:
        -
          name: expression
          in: body
          description: A rich information Sentence
          schema:
            type: object
            properties:
              sentence:
                type: string
              entityList:
                type: array
                items:
                  type: string
              inlineEntities:
                type: array
                items:
                  type: object
                  required:
                    - entityId
                  properties:
                    entityId:
                      type: string
                    start:
                      type: integer
                      format: int64
                    end:
                      type: integer
                      format: int64
          required: true
                
              
          
      responses:
        201:
          description: Successful created new `Expression`
    